
server:
  port: 7070
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: user-service
  security:
    user:
      name: 'user'
      password: 'user'
jwt:
  secret: "dlkjflkdjlkdjflkdfdfdffdfdddfddfdfdfdfdfdfdfddffddgsaadfdsdsdsfsgddgdggdsgdsgdsdsdsgdssgdgdsgdsgdsgdsdsdsgdsgdsdsgdsgds"
  expiration: 400000 # 24 hours in milliseconds

